
version: '3.8'

services:

  frontend:
    build: ./frontend/.
    depends_on:
      - backend    
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - idade-network
   
          
  backend:
    build: ./backend/.
    depends_on:
      - db        
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_NAME: users    
    secrets:
      - mysql_password
    networks:
      - idade-network
     

  db:
    image: mysql:8.0.39-debian
    container_name: db    
    restart: always
    environment:      
      MYSQL_DATABASE: users
      MYSQL_USER: user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    secrets:
      - mysql_root_password
      - mysql_password
    volumes:
      - db-data-idade:/var/lib/mysql  
  
      
    ports:
      - '3306:3306'
    networks:
      - idade-network
    


volumes:
  db-data-idade:
    driver: local
  

networks:
  idade-network:
 

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt 
  mysql_password:
    file: ./secrets/mysql_password.txt 